# Generated by Django 5.0.6 on 2024-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'get_latest_by': ['id']},
        ),
        migrations.AddField(
            model_name='query',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
