# Generated by Django 5.0.6 on 2024-05-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0002_alter_query_options_query_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
